#!/bin/sh

# This initial setup is essential, so abort if anything fails.
set -e

orig_dir="$(pwd)"
export GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa.gpii-ci'
git config --global user.email "gpii-bot@gpii.net"
git config --global user.name "GPII Bot"

# When an existing container is restarted, the sandbox is left behind. Clear it
# out and start over.
rm -rf gpii-infra
# We don't need the full history, but we want a few previous revisions in case
# we need those revisions to push to a remote (e.g. gitlab) that hasn't been
# updated in a bit.
git clone --depth 10 git@github.com:gpii-ops/gpii-infra
cd gpii-infra/aws/modules/deploy
git remote add gitlab git@gitlab.com:gpii-ops/gpii-infra

# Failures in the main loop are ok, so continue if anything fails and try again
# on the next go around.
set +e
while true ; do
    echo "Starting version check at $(date)"
    git fetch --all --tags -p
    git reset --hard origin/master

    "$orig_dir/update-version"
    if [ -n "$(git status --porcelain -- version.yml)" ]; then
        git add version.yml
        git commit -m"[auto] Update version.yml"
        git push origin HEAD
        git push gitlab HEAD
    fi

    sleep_secs=300
    echo "Finished version check at $(date)"
    echo "Sleeping $sleep_secs..."
    sleep $sleep_secs
done
